-- Playlist seed: 27 Spotify + 13 cross-platform (run after migration 001)
WITH dna AS (SELECT '["Larry June","Dom Kennedy","Freddie Gibbs","Stove God Cooks","Boldy James","Nipsey Hussle","Wale","J Cole"]'::jsonb AS s)
INSERT INTO playlist_targets (playlist_id,platform,playlist_name,curator_name,track_name,follower_count,track_count,overlap_score,fraud_score,fraud_verdict,pitch_status,research_context,curator_email,submission_url,submission_method,tier,whitelist_status,legitimacy_score,vibe_tags,similar_artists,is_active)
SELECT * FROM (
  SELECT '74Xl4zj1bRifx7DvDy1amd','spotify','rap gems','SlapMusic',NULL,79900,0,0,85,'safe','not_pitched','{"source":"seed"}'::jsonb,'rapgems@pm.me','https://open.spotify.com/playlist/74Xl4zj1bRifx7DvDy1amd','email',2,false,85,'["underground","hip_hop"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '0mSf78pnq5xVU6kOtdv6dx','spotify','Chill Rap Playlist','Promoting Sounds',NULL,191500,0,0,80,'safe','not_pitched','{"source":"seed"}'::jsonb,'PromotingSoundsSpotify@gmail.com','https://open.spotify.com/playlist/0mSf78pnq5xVU6kOtdv6dx','email',2,false,80,'["chill","rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '38rSkTivyQzJ6C2SMz4YzO','spotify','Rap Bops','Daily Rap Facts',NULL,15000,0,0,75,'safe','not_pitched','{"source":"seed"}'::jsonb,'dailyrapfacts@gmail.com','https://open.spotify.com/playlist/38rSkTivyQzJ6C2SMz4YzO','email',2,false,75,'["rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-todays-rap-hits','spotify','Todays Rap Hits','Clay Buckner',NULL,41000,0,0,65,'suspicious','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,'Todaysraphits@gmail.com',NULL,'email',3,false,65,'["rap","hits"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-musicarray-rap-gems','spotify','Rap Gems underground','MusicArray',NULL,5000,0,0,78,'safe','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,'tomusicarray@gmail.com',NULL,'email',2,false,78,'["underground","rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-musicarray-lowkey-rap','spotify','Lowkey Rap','MusicArray',NULL,3000,0,0,78,'safe','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,'tomusicarray@gmail.com',NULL,'email',2,false,78,'["underground","rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-top-rap','spotify','Top Rap','Playlister Network',NULL,8000,0,0,70,'safe','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,'submit.playlisternetwork@gmail.com',NULL,'email',2,false,70,'["rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-rap-hip-hop-place-in-sound','spotify','Rap and Hip Hop','Place in Sound',NULL,3000,0,0,72,'safe','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,'SubmitYourMusic@protonmail.com',NULL,'email',2,false,72,'["rap","hip_hop"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-rap-nation-no-label','spotify','Rap Nation No Label','Rap Nation',NULL,20000,0,0,78,'safe','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,NULL,'https://docs.google.com/forms/d/e/1FAIpQLSeau5uJirsrSj-LjBaZ5LxxlhcCLjt29ky4Lfy7pBWmCvxTwQ/viewform','google_form',2,false,78,'["rap","indie"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-hip-hop-hits-starstorm','spotify','Hip-Hop Hits','Starstorm Playlists',NULL,10000,0,0,72,'safe','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,NULL,'https://www.toneden.io/starstormplaylists/post/submit-your-music','web_form',2,false,72,'["hip_hop","hits"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '1NjQR0evUqgnVWOQVn8cci','spotify','Chill Rap and Hip Hop','Curatify',NULL,362400,0,0,70,'suspicious','not_pitched','{"source":"seed","notes":"Verify first"}'::jsonb,NULL,'https://open.spotify.com/playlist/1NjQR0evUqgnVWOQVn8cci','submithub',3,false,70,'["chill","rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '63yrnUYe65gXwNN7lH935u','spotify','Chill Rap Vibes 2026','Bass Lovers',NULL,95600,0,0,65,'suspicious','not_pitched','{"source":"seed","notes":"Verify first"}'::jsonb,NULL,'https://open.spotify.com/playlist/63yrnUYe65gXwNN7lH935u','submithub',3,false,65,'["chill","rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '6V7TOG2nLC3jUmSb9PxsYc','spotify','Chill Rap 2026','indiemono',NULL,17500,0,0,95,'safe','not_pitched','{"source":"seed","notes":"Bot-free network"}'::jsonb,NULL,'https://indiemono.com/submit-music-chill-playlists/','indiemono',1,true,95,'["chill","rap","editorial"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '6b9WdOHKpTgSGspBYT8Uf1','spotify','Cali Vibe Dom Kennedy Larry June','Michael',NULL,874,0,0,90,'safe','not_pitched','{"source":"seed","notes":"Strong DNA match"}'::jsonb,NULL,'https://open.spotify.com/playlist/6b9WdOHKpTgSGspBYT8Uf1','spotify_dm',1,true,90,'["west_coast","larry_june","dom_kennedy"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '3puh7BBfeSp2ewAiX6hCrm','spotify','Spiritual Hip Hop Rap','i.mctzma',NULL,1400,0,0,92,'safe','not_pitched','{"source":"seed","notes":"Meditation fit"}'::jsonb,NULL,'https://open.spotify.com/playlist/3puh7BBfeSp2ewAiX6hCrm','spotify_dm',1,true,92,'["spiritual","conscious","meditation"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '5KRz9DYjQ6UwGeWNmGvGjz','spotify','Best of Griselda Freddie Gibbs Boldy James','DamnDev Radio',NULL,1800,0,0,88,'safe','not_pitched','{"source":"seed","notes":"Core DNA comps"}'::jsonb,NULL,'https://open.spotify.com/playlist/5KRz9DYjQ6UwGeWNmGvGjz','spotify_dm',1,true,88,'["griselda","underground"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '3Rsku9pxYmar0ozyHY52Uy','spotify','West Coast Rap Vibes 2026','Kaptivate World',NULL,910,0,0,75,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://open.spotify.com/playlist/3Rsku9pxYmar0ozyHY52Uy','spotify_dm',2,false,75,'["west_coast","rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '55bJM4Pn2vXp3ahIr6pf1k','spotify','Spiritual Conscious Hip-Hop RnB','alongyourpath',NULL,231,0,0,90,'safe','not_pitched','{"source":"seed","notes":"Holistic niche"}'::jsonb,NULL,'https://open.spotify.com/playlist/55bJM4Pn2vXp3ahIr6pf1k','spotify_dm',1,true,90,'["spiritual","conscious","holistic"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '0czSeyVyVZoYv0x44nu4K3','spotify','Conscious Rap','Timothy Walschaerts',NULL,7700,0,0,78,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://open.spotify.com/playlist/0czSeyVyVZoYv0x44nu4K3','spotify_dm',2,false,78,'["conscious","rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '7H8IqZTV2SsYpA5vjiAdhD','spotify','Conscious Rap v2','Adam Argyle',NULL,666,0,0,75,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://open.spotify.com/playlist/7H8IqZTV2SsYpA5vjiAdhD','spotify_dm',2,false,75,'["conscious","rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-spiritual-hip-hop-lari','spotify','Spiritual Hip Hop Rap Lari','Lari Keeler',NULL,59,0,0,88,'safe','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,NULL,NULL,'spotify_dm',1,true,88,'["spiritual","hip_hop"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-bass-car-songs-genzahead','spotify','Bass Car Songs Hip Hop 2026','GenZAhead',NULL,5000,0,0,68,'suspicious','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,NULL,NULL,'instagram_dm',3,false,68,'["trap","808s"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-gym-hip-hop-slappers','spotify','Gym Hip Hop','SLAPPERS',NULL,4000,0,0,70,'safe','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,'slappersplaylists@gmail.com',NULL,'email',2,false,70,'["gym","hip_hop"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-rapwrld-tohiphophub','spotify','RapWRLD ToHipHopHub','ToHipHopHub',NULL,8000,0,0,72,'safe','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,'tohiphophub@gmail.com',NULL,'email',2,false,72,'["rap","hip_hop"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-drip-hop-high-road','spotify','Drip Hop','High Road Publicity',NULL,5000,0,0,75,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://highroadpublicity.com/submissions/','web_form',2,false,75,'["rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'pending-chill-rap-songs-2026','spotify','Chill Rap Songs 2026','Chill Select',NULL,10900,0,0,75,'safe','not_pitched','{"source":"seed","flags":["needs_spotify_id"]}'::jsonb,NULL,NULL,'dailyplaylists',2,false,75,'["chill","rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT '1v4toGP8BDz8NTG0Ahxv3M','spotify','Chill Hip Hop Vibes 2026','IndieMassive',NULL,66100,0,0,60,'suspicious','not_pitched','{"source":"seed","notes":"Verify first"}'::jsonb,NULL,'https://open.spotify.com/playlist/1v4toGP8BDz8NTG0Ahxv3M','submithub',3,false,60,'["chill","hip_hop"]'::jsonb,dna.s,true FROM dna
) AS v(playlist_id,platform,playlist_name,curator_name,track_name,follower_count,track_count,overlap_score,fraud_score,fraud_verdict,pitch_status,research_context,curator_email,submission_url,submission_method,tier,whitelist_status,legitimacy_score,vibe_tags,similar_artists,is_active)
ON CONFLICT (playlist_id) DO UPDATE SET playlist_name=EXCLUDED.playlist_name,curator_name=EXCLUDED.curator_name,follower_count=EXCLUDED.follower_count,fraud_verdict=EXCLUDED.fraud_verdict,research_context=EXCLUDED.research_context,curator_email=EXCLUDED.curator_email,submission_url=EXCLUDED.submission_url,submission_method=EXCLUDED.submission_method,tier=EXCLUDED.tier,whitelist_status=EXCLUDED.whitelist_status,legitimacy_score=EXCLUDED.legitimacy_score,vibe_tags=EXCLUDED.vibe_tags,similar_artists=EXCLUDED.similar_artists,is_active=EXCLUDED.is_active,updated_at=now();
-- Cross-platform (SoundCloud, YouTube, Apple Music, Blogs)
WITH dna AS (SELECT '["Larry June","Dom Kennedy","Freddie Gibbs"]'::jsonb AS s)
INSERT INTO playlist_targets (playlist_id,platform,playlist_name,curator_name,track_name,follower_count,track_count,overlap_score,fraud_score,fraud_verdict,pitch_status,research_context,curator_email,submission_url,submission_method,tier,whitelist_status,legitimacy_score,vibe_tags,similar_artists,is_active)
SELECT * FROM (
  SELECT 'soundcloud:run_the_trap','soundcloud','RUN THE TRAP','Run The Trap',NULL,NULL,0,0,85,'safe','not_pitched','{"source":"seed"}'::jsonb,'rttsubmit@gmail.com','https://runthetrap.com','email',2,true,85,'["trap","hip_hop"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'soundcloud:trap_deep_focus','soundcloud','Trap for Deep Focus','SoundCloud',NULL,NULL,0,0,70,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://soundcloud.com/discover','algorithmic',2,false,70,'["chill_trap","meditation"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'soundcloud:official_hiphop','soundcloud','SoundCloud HipHop submissions','SoundCloud',NULL,NULL,0,0,72,'safe','not_pitched','{"source":"seed"}'::jsonb,'musicsubmissionsuk@gmail.com',NULL,'email',2,false,72,'["hip_hop"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'soundcloud:weekend_chill_rap','soundcloud','Weekend Chill Rap','SoundCloud Discovery',NULL,NULL,0,0,70,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://soundcloud.com/discover','algorithmic',2,false,70,'["chill","rap"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'youtube:run_the_trap_tv','youtube','Run The Trap TV','Run The Trap',NULL,240000,0,0,85,'safe','not_pitched','{"source":"seed"}'::jsonb,'rttsubmit@gmail.com','https://www.youtube.com','email',2,true,85,'["trap","youtube"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'youtube:indiy_hip_hop','youtube','Indiy Hip Hop Playlists','Indiy',NULL,NULL,0,0,70,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://indiy.com/job/Submit/soundcloud-playlist-hip-hop/','web_form',2,false,70,'["hip_hop","indie"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'apple_music:chill_rap_editorial','apple_music','Chill Rap Editorial','Apple Music Editors',NULL,NULL,0,0,80,'safe','not_pitched','{"source":"seed","notes":"Via distributor"}'::jsonb,NULL,'https://music.apple.com','distributor_pitch',2,false,80,'["chill","rap","editorial"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'apple_music:rap_life_editorial','apple_music','Rap Life Editorial','Apple Music Ebro Darden',NULL,NULL,0,0,80,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://music.apple.com','distributor_pitch',2,false,80,'["rap","editorial"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'blog:earmilk','blog','Earmilk','Earmilk',NULL,NULL,0,0,75,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://earmilk.com','submithub',2,false,75,'["blog","hip_hop"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'blog:lyrical_lemonade','blog','Lyrical Lemonade','Lyrical Lemonade',NULL,NULL,0,0,78,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://www.lyricallemonade.com','submithub',2,false,78,'["blog","hip_hop"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'blog:word_is_bond','blog','The Word Is Bond','TWIB',NULL,NULL,0,0,72,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://wordisbond.com','web_form',2,false,72,'["conscious","lyrics"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'blog:sphere_of_hiphop','blog','Sphere of Hip-Hop','Sphere of Hip-Hop',NULL,NULL,0,0,74,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://www.submithub.com/playlister/sphere-of-hip-hop','submithub',2,false,74,'["hip_hop","spiritual"]'::jsonb,dna.s,true FROM dna UNION ALL
  SELECT 'blog:artistrack','blog','ArtistRack','ArtistRack',NULL,NULL,0,0,70,'safe','not_pitched','{"source":"seed"}'::jsonb,NULL,'https://artistrack.com','web_form',2,false,70,'["blog","indie"]'::jsonb,dna.s,true FROM dna
) AS v(playlist_id,platform,playlist_name,curator_name,track_name,follower_count,track_count,overlap_score,fraud_score,fraud_verdict,pitch_status,research_context,curator_email,submission_url,submission_method,tier,whitelist_status,legitimacy_score,vibe_tags,similar_artists,is_active)
ON CONFLICT (playlist_id) DO UPDATE SET playlist_name=EXCLUDED.playlist_name,fraud_verdict=EXCLUDED.fraud_verdict,research_context=EXCLUDED.research_context,curator_email=EXCLUDED.curator_email,submission_url=EXCLUDED.submission_url,submission_method=EXCLUDED.submission_method,tier=EXCLUDED.tier,whitelist_status=EXCLUDED.whitelist_status,legitimacy_score=EXCLUDED.legitimacy_score,vibe_tags=EXCLUDED.vibe_tags,similar_artists=EXCLUDED.similar_artists,is_active=EXCLUDED.is_active,updated_at=now();
